spring.application.name=rewards-application
server.port=8080
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.info.env.enabled=true
info.app.name=Rewards Application
info.app.description=Project used for Rewards Application Integration
info.app.version=1.0.0
info.app.developer=Sajith V J
