DROP TABLE IF EXISTS TESTDB;

CREATE TABLE TESTDB(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS TRANSACTION;

CREATE TABLE TRANSACTION(
    TRANSACTION_ID VARCHAR(255) NOT NULL,
    CUSTOMER_ID VARCHAR(255),
    CUSTOMER_NAME VARCHAR(255),
    AMOUNT DECIMAL(10,2),
    TRANSACTION_DATE DATE,
    PRIMARY KEY(TRANSACTION_ID)
);